
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace OrderTest
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Order()
    {

        this.OrderDetails = new HashSet<OrderDetail>();

    }


    public string OrderID { get; set; }

    public string MemberID { get; set; }

    public Nullable<System.DateTime> OrderDate { get; set; }

    public Nullable<decimal> OrderTotalPrice { get; set; }

    public Nullable<int> CheckInPeople { get; set; }

    public Nullable<int> ActivityID { get; set; }

    public string OrderRemark { get; set; }

    public string OrderClosed { get; set; }



    public virtual Activity Activity { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetail> OrderDetails { get; set; }

    public virtual RoomMember RoomMember { get; set; }

}

}
